name: Docker Build

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: my-image

jobs:
  prepare-env-vars:
    name: Prepare env vars
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      SHORT_SHA: ${{ steps.create-tag.outputs.SHORT_SHA }}
      GITHUB_REPO_OWNER: ${{ steps.lowercase-github-repo-owner-name.outputs.GITHUB_REPO_OWNER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Create Tag
        id: create-tag
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
       # This step is required as the GHCR repository owner name must be lower case in order to build and push images.
      - name: Lowercase GitHub Repo Owner Name
        id: lowercase-github-repo-owner-name
        run: echo "GITHUB_REPO_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: prepare-env-vars

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: GitHub Container Registry Login
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        run: docker build -t ${{ env.REGISTRY }}/${{ needs.prepare-env-vars.outputs.GITHUB_REPO_OWNER }}/${{ env.IMAGE_NAME }}:${{ needs.prepare-env-vars.outputs.SHORT_SHA }} -f source/Dockerfile ./source