name: Python CI

on:
  push:
    paths:
      - 'source/**'
  pull_request:
    paths:
      - 'source/**'

env:
  PYTHON_VERSION: "3.13"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with: 
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Dev Dependencies
        run: pip install -r app/requirements-dev.txt

      - name: Run Flake8
        run: flake8 app/
        continue-on-error: true
        