name: Python CI

on:
  push:
    paths:
      - 'source/**'
  pull_request:
    paths:
      - 'source/**'

env:
  PYTHON_VERSION: "3.13"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
