name: Python CI

on:
  push:
    branches:
      - main
    # paths:
    #   - 'source/**'
  pull_request:
    paths:
      - 'source/**'

env:
  PYTHON_VERSION: "3.13"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with: 
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Dev Dependencies (Staging)
        if: github.ref == 'refs/heads/staging'
        run: pip install -r source/requirements-dev.txt
      
      - name: Install Dev Dependencies (Production)
        if: github.ref == 'refs/heads/main'
        run: pip install -r source/requirements.txt

      - name: Run Flake8
        run: flake8 source/
        continue-on-error: true
  
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install Dev Dependencies
        run: | 
          pip install -r source/requirements-dev.txt
          pip install -r source/requirements.txt

      - name: Run Pytest
        run: python -m pytest source/tests/tests.py -v --junitxml="version-${{ matrix.python-version }}-pytest-results.xml"
        continue-on-error: true

      - name: Upload Pytest Results Artifact
        uses: actions/upload-artifact@v7
        with:
          name: version-${{ matrix.python-version }}-pytest-results
          path: version-${{ matrix.python-version }}-pytest-results.xml

  docker-build:
    name: Docker Build
    uses: ./.github/workflows/docker-build.yaml
    needs:
      - lint
      - test
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
  slack-notification-on-failure:
    name: Slack Notification on failure
    if: always() && github.ref == 'refs/heads/main' && needs.docker-build.result == 'failure'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - docker-build
    steps:
      - name: slack-notifier
        uses: slackapi/slack-github-action@v3.0.3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*<!here> Docker Build Failed!*\nClick <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|here> for the workflow run"